export const menuLeftData = [
    {
        id:1,
        icon:"/components/NavbarLeft/icons/1.svg",
        text:"Trading",
        link:"trading",
    },
    {
        id:2,
        icon:"/components/NavbarLeft/icons/2.svg",
        text:"Billing",
        link:"billing",
    },
    {
        id:3,
        icon:"/components/NavbarLeft/icons/3.svg",
        text:"Settings",
        link:"settings",
    },
    {
        id:4,
        icon:"/components/NavbarLeft/icons/4.svg",
        text:"Theme",
        link:"theme",
    },
    {
        id:5,
        icon:"/components/NavbarLeft/icons/5.svg",
        text:"Referral",
        link:"referral",
    },
    {
        id:6,
        icon:"/components/NavbarLeft/icons/6.svg",
        text:"Funds",
        link:"funds",
    },
    {
        id:7,
        icon:"/components/NavbarLeft/icons/7.svg",
        text:"Tour",
        link:"tour",
    },
    {
        id:8,
        icon:"/components/NavbarLeft/icons/8.svg",
        text:"Sign Out",
        link:"sigOut",
    },
]
